#
# Copyright (C) 2019 Vdaas.org Vald team ( kpango, kou-m, rinx )
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agent-ngt
  name: agent-ngt
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: agent-ngt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: agent-ngt
    spec:
      containers:
      - image: vdaas/vald-agent-ngt:nightly
        imagePullPolicy: Always 
        # livenessProbe:
        #   httpGet:
        #     path: /liveness
        #     port: liveness
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 2
        #   periodSeconds: 3
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: readiness
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 2
        #   periodSeconds: 3
        name: agent-ngt
        ports:
        - containerPort: 3000
          name: liveness
          protocol: TCP
        - containerPort: 3001
          name: readiness
          protocol: TCP
        - containerPort: 8082
          name: grpc
          protocol: TCP
        - containerPort: 8080
          name: rest
          protocol: TCP
        - containerPort: 6060
          name: pprof
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/server/
          name: agent-ngt-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: agent-ngt-config
        name: agent-ngt-config
status:
