#
# Copyright (C) 2019-2020 Vdaas.org Vald team ( kpango, rinx, kmrmt )
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{- if and .Values.meta.enabled (eq .Values.meta.kind "DaemonSet") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.Values.meta.name }}
  labels:
    app: {{ .Values.meta.name }}
    app.kubernetes.io/name: {{ include "vald.name" . }}
    helm.sh/chart: {{ include "vald.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: meta
  {{- if .Values.meta.annotations }}
  annotations:
    {{- toYaml .Values.meta.annotations | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.meta.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.meta.name }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.meta.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.meta.name }}
        app.kubernetes.io/name: {{ include "vald.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: meta
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/meta/configmap.yaml") . | sha256sum }}
        {{- if .Values.meta.podAnnotations }}
        {{- toYaml .Values.meta.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.meta.initContainers }}
      initContainers:
        {{- $initContainers := dict "initContainers" .Values.meta.initContainers "Values" .Values "namespace" .Release.Namespace -}}
        {{- include "vald.initContainers" $initContainers | trim | nindent 8 }}
      {{- end }}
      affinity:
        {{- include "vald.affinity" .Values.meta.affinity | nindent 8 }}
      {{- if .Values.meta.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.meta.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.meta.name }}
          image: "{{ .Values.meta.image.repository }}:{{ default .Values.defaults.image.tag .Values.meta.image.tag }}"
          imagePullPolicy: {{ .Values.meta.image.pullPolicy }}
          {{- $servers := dict "Values" .Values.meta.server_config "default" .Values.defaults.server_config -}}
          {{- include "vald.containerPorts" $servers | trim | nindent 10 }}
          resources:
            {{- toYaml .Values.meta.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{- if .Values.meta.env }}
          env:
            {{- toYaml .Values.meta.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.meta.name }}-config
              mountPath: /etc/server/
            {{- if .Values.meta.volumeMounts }}
            {{- toYaml .Values.meta.volumeMounts | nindent 12 }}
            {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: {{ .Values.meta.terminationGracePeriodSeconds }}
      volumes:
        - name: {{ .Values.meta.name }}-config
          configMap:
            defaultMode: 420
            name: {{ .Values.meta.name }}-config
        {{- if .Values.meta.volumes }}
        {{- toYaml .Values.meta.volumes | nindent 8 }}
        {{- end }}
      {{- if .Values.meta.nodeName }}
      nodeName: {{ .Values.meta.nodeName }}
      {{- end }}
      {{- if .Values.meta.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.meta.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.tolerations }}
      tolerations:
        {{- toYaml .Values.meta.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.podPriority }}
      {{- if .Values.meta.podPriority.enabled }}
      priorityClassName: {{ .Values.meta.name }}-priority
      {{- end }}
      {{- end }}
status:
{{- end }}
