#
# Copyright (C) 2019-2026 vdaas.org vald team <vald@vdaas.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
[package]
name = "agent"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algorithm = { version = "0.1.0", path = "../../libs/algorithm" }
qbg = { version = "0.1.0", path = "../../libs/algorithms/qbg" }
kvs = { version = "0.1.0", path = "../../libs/kvs" }
observability = { version = "0.1.0", path = "../../libs/observability" }
anyhow = "1.0.101"
async-trait = "0.1"
chrono = "0.4.43"
config = "0.15.19"
flexi_logger = "0.31"
futures = "0.3.32"
gethostname = "1.1"
http = "1.4.0"
k8s-openapi = { version = "0.27", features = ["v1_35"] }
kube = { version = "3.0", features = ["runtime", "client", "derive"] }
log = "0.4"
opentelemetry = { version = "0.31.0" }
prost = "0.14.3"
prost-types = "0.14.3"
proto = { version = "0.1.0", path = "../../libs/proto" }
thiserror = "2.0"
tokio = { version = "1.49.0", features = ["full"] }
tokio-stream = { version = "0.1.18", features = ["full"] }
tokio-util = "0.7"
tonic = "0.14.4"
tonic-types = "0.14.4"
tower = "0.5.3"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
vqueue = { version = "0.1.0", path = "../../libs/vqueue" }
axum = "0.8.8"

[dev-dependencies]
bytes = "1.11.1"
http-body = "1.0.1"
tempfile = "3"
rand = "0.10"
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio", "testing"] }
rand_distr = "0.6.0"
