#
# Copyright (C) 2019-2020 Vdaas.org Vald team ( kpango, rinx, kmrmt )
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{- if eq .Values.compressor.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.compressor.name }}
  labels:
    app: {{ .Values.compressor.name }}
spec:
  progressDeadlineSeconds: {{ .Values.compressor.progressDeadlineSeconds }}
  replicas: {{ .Values.compressor.minReplicas }}
  revisionHistoryLimit: {{ .Values.compressor.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.compressor.name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.compressor.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.compressor.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.compressor.name }}
    spec:
      {{- if .Values.compressor.initContainers }}
      initContainers:
        {{- $initContainers := dict "initContainers" .Values.compressor.initContainers "Values" .Values "namespace" .Release.Namespace -}}
        {{- include "vald.initContainers" $initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.compressor.name }}
          image: "{{ .Values.compressor.image.repository }}:{{ .Values.compressor.image.tag }}"
          imagePullPolicy: {{ .Values.compressor.image.pullPolicy }}
          {{- $servers := dict "Values" .Values.compressor.server_config "default" .Values.defaults.server_config }}
          {{- include "vald.containerPorts" $servers | nindent 10 }}
          resources:
            {{- toYaml .Values.compressor.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            {{- toYaml .Values.compressor.env | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.compressor.name }}-config
              mountPath: /etc/server/
            {{- if .Values.compressor.volumeMounts }}
            {{- toYaml .Values.compressor.volumeMounts | nindent 12 }}
            {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: {{ .Values.compressor.terminationGracePeriodSeconds }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ .Values.compressor.name }}-config
          name: {{ .Values.compressor.name }}-config
        {{- if .Values.compressor.volumes }}
        {{- toYaml .Values.compressor.volumes | nindent 8 }}
        {{- end }}
status:
{{- end }}
