#
# Copyright (C) 2019-2020 Vdaas.org Vald team ( kpango, rinx, kmrmt )
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

gateway:
  minReplicas: 1
  hpa:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
  gateway_config:
    index_replica: 3

agent:
  minReplicas: 3
  maxReplicas: 10
  podManagementPolicy: Parallel
  hpa:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
  ngt:
    auto_index_limit: 60s
    auto_index_check_duration: 5s
    auto_index_length: 10
    dimension: 6

discoverer:
  minReplicas: 1
  hpa:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 50Mi

compressor:
  minReplicas: 1
  hpa:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
  compress:
    compress_algorithm: gob

backupManager:
  minReplicas: 1
  hpa:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 30Mi

indexManager:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 30Mi

meta:
  minReplicas: 1
  hpa:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 30Mi
