#
# Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{- $agent := .Values.agent -}}
{{- $readreplica := .Values.agent.readreplica -}}
{{- $defaults := .Values.defaults -}}
{{- $release := .Release -}}
{{- $chart := .Chart -}}
{{- $valdname := include "vald.name" . -}}
{{- $valdchart := include "vald.chart" . -}}
# if agent.enabled is true and agent.kind is StatefulSet and readreplica.enabled is true
# then create StatefulSet for agent and readreplica
{{- if and $agent.enabled (eq .Values.agent.kind "StatefulSet") $readreplica.enabled }}
{{ range $id := until (int $agent.minReplicas) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $readreplica.name }}-{{ $id }}
  labels:
    app: {{ $readreplica.name }}-{{ $id }}
    app.kubernetes.io/name: {{ $valdname }}
    helm.sh/chart: {{ $valdchart }}
    app.kubernetes.io/managed-by: {{ $release.Service }}
    app.kubernetes.io/instance: {{ $release.Name }}
    app.kubernetes.io/version: {{ $chart.Version }}
    app.kubernetes.io/component: agent-replica
    {{ $readreplica.label_key }}: "{{ $id }}"
  {{- if $agent.annotations }}
  annotations:
    {{- toYaml $agent.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not $agent.hpa.enabled }}
  replicas: {{ $readreplica.replica }}
  {{- end }}
  revisionHistoryLimit: {{ $agent.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $readreplica.name }}-{{ $id }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ $readreplica.name }}-{{ $id }}
        app.kubernetes.io/name: {{ $valdname }}
        app.kubernetes.io/instance: {{ $release.Name }}
        app.kubernetes.io/component: agent-replica
      {{- $pprof := default $defaults.server_config.metrics.pprof $agent.server_config.metrics.pprof }}
      {{- if or $agent.podAnnotations $agent.sidecar.enabled $pprof.enabled }}
      annotations:
        {{- if $agent.podAnnotations }}
        {{- toYaml $agent.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if $pprof.enabled }}
        pyroscope.io/scrape: "true"
        pyroscope.io/application-name: {{ $agent.name }}
        pyroscope.io/profile-cpu-enabled: "true"
        pyroscope.io/profile-mem-enabled: "true"
        pyroscope.io/port: "{{ $pprof.port }}"
        {{- end }}
        {{- if $agent.sidecar.enabled }}
        checksum/configmap: {{ include (print $.Template.BasePath "/agent/configmap.yaml") . | sha256sum }}
        checksum/sidecar-configmap: {{ include (print $.Template.BasePath "/agent/sidecar-configmap.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      {{- if or $agent.initContainers $agent.sidecar.initContainerEnabled }}
      initContainers:
        {{- if $agent.initContainers }}
        {{- $initContainers := dict "initContainers" $agent.initContainers "Values" .Values "namespace" .Release.Namespace -}}
        {{- include "vald.initContainers" $initContainers | trim | nindent 8 }}
        {{- end }}
        {{- if $agent.sidecar.initContainerEnabled }}
        - name: {{ $agent.sidecar.name }}-init
          image: "{{ $agent.sidecar.image.repository }}:{{ default $defaults.image.tag $agent.sidecar.image.tag }}"
          imagePullPolicy: {{ $agent.sidecar.image.pullPolicy }}
          {{- $servers := dict "Values" $agent.sidecar.server_config "default" $defaults.server_config -}}
          {{- include "vald.containerPorts" $servers | trim | nindent 10 }}
          resources:
            {{- toYaml $agent.sidecar.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{- if $agent.securityContext }}
          securityContext:
            {{- toYaml $agent.securityContext | nindent 12 }}
          {{- end }}
          env:
            - name: VALD_AGENT_SIDECAR_MODE
              value: "initcontainer"
            {{- if $agent.sidecar.env }}
            {{- toYaml $agent.sidecar.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{ $agent.sidecar.name }}-config
              mountPath: /etc/server/
            {{- if not $agent.ngt.enable_in_memory_mode }}
            {{- if $agent.ngt.index_path }}
            {{- if $agent.persistentVolume.enabled }}
            - name: {{ $agent.name }}-pvc
              mountPath: {{ dir $agent.ngt.index_path }}
              mountPropagation: {{ $agent.persistentVolume.mountPropagation }}
            {{- else }}
            - name: {{ $agent.name }}-local
              mountPath: {{ dir $agent.ngt.index_path }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if $agent.volumeMounts }}
            {{- toYaml $agent.volumeMounts | nindent 12 }}
            {{- end }}
        {{- end }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ $readreplica.name }}-{{ $id }}
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- if $agent.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml $agent.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $agent.name }}
          image: "{{ $agent.image.repository }}:{{ default $defaults.image.tag $agent.image.tag }}"
          imagePullPolicy: {{ $agent.image.pullPolicy }}
          {{- $servers := dict "Values" $agent.server_config "default" $defaults.server_config -}}
          {{- include "vald.containerPorts" $servers | trim | nindent 10 }}
          resources:
            {{- toYaml $agent.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{- if $agent.securityContext }}
          securityContext:
            {{- toYaml $agent.securityContext | nindent 12 }}
          {{- end }}
          {{- if $agent.env }}
          env:
            {{- toYaml $agent.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ $agent.name }}-config
              mountPath: /etc/server/
            {{- if not $agent.ngt.enable_in_memory_mode }}
            {{- if $agent.ngt.index_path }}
            {{- if $agent.persistentVolume.enabled }}
            - name: {{ $readreplica.volume_name }}
              mountPath: {{ dir $agent.ngt.index_path }}
              mountPropagation: {{ $agent.persistentVolume.mountPropagation }}
            {{- else }}
            - name: {{ $agent.name }}-local
              mountPath: {{ dir $agent.ngt.index_path }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if $agent.volumeMounts }}
            {{- toYaml $agent.volumeMounts | nindent 12 }}
            {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- if $agent.podSecurityContext }}
      securityContext:
        {{- toYaml $agent.podSecurityContext | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $agent.terminationGracePeriodSeconds }}
      volumes:
        - name: {{ $agent.name }}-config
          configMap:
            defaultMode: 420
            name: {{ $agent.name }}-config
        - name: {{ $readreplica.volume_name }}
          persistentVolumeClaim:
            claimName: {{ $readreplica.name }}-pvc-{{ $id }}
      {{- if $agent.nodeName }}
      nodeName: {{ $agent.nodeName }}
      {{- end }}
      {{- if $agent.nodeSelector }}
      nodeSelector:
        {{- toYaml $agent.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $agent.tolerations }}
      tolerations:
        {{- toYaml $agent.tolerations | nindent 8 }}
      {{- end }}
      {{- if $agent.podPriority }}
      {{- if $agent.podPriority.enabled }}
      priorityClassName: {{ $release.Namespace }}-{{ $agent.name }}-priority
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
