#
# Copyright (C) 2019-2020 Vdaas.org Vald team ( kpango, rinx, kmrmt )
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.indexManager.name }}-config
data:
  config.yaml: |
    ---
    version: {{ .Values.indexManager.version }}
    time_zone: {{ default .Values.defaults.time_zone .Values.indexManager.time_zone }}
    {{- if .Values.indexManager.logging }}
    logging:
      logger: {{ .Values.indexManager.logging.logger }}
      level: {{ .Values.indexManager.logging.level }}
      format: {{ .Values.indexManager.logging.format }}
    {{- end }}
    server_config:
      {{- $servers := dict "Values" .Values.indexManager.server_config "default" .Values.defaults.server_config }}
      {{- include "vald.servers" $servers | nindent 6 }}
    indexer:
      agent_port: {{ default .Values.defaults.server_config.servers.grpc.port .Values.agent.server_config.servers.grpc.port }}
      agent_name: {{ .Values.agent.name }}
      agent_namespace: {{ .Release.Namespace }}
      agent_dns: {{ .Values.agent.name }}.{{ .Release.Namespace }}.svc.cluster.local
      discoverer:
        host: {{ .Values.discoverer.name }}.{{ .Release.Namespace }}.svc.cluster.local
        port: {{ default .Values.defaults.server_config.servers.grpc.port .Values.discoverer.server_config.servers.grpc.port }}
        duration: {{ .Values.indexManager.indexer.discoverer.duration }}
        discover_client:
          {{- $discoverClient := dict "Values" .Values.indexManager.indexer.discoverer.discover_client "default" .Values.defaults.grpc.client }}
          {{- include "vald.grpc.client" $discoverClient | nindent 10 }}
        agent_client:
          {{- $agentClient := dict "Values" .Values.indexManager.indexer.discoverer.agent_client "default" .Values.defaults.grpc.client }}
          {{- include "vald.grpc.client" $agentClient | nindent 10 }}
      concurrency: {{ .Values.indexManager.indexer.concurrency }}
      auto_index_duration_limit: {{ .Values.indexManager.indexer.auto_index_duration_limit }}
      auto_index_check_duration: {{ .Values.indexManager.indexer.auto_index_check_duration }}
      auto_index_length: {{ .Values.indexManager.indexer.auto_index_length }}
