name: build protobuf
on:
  push:
    branches:
      - master
    paths:
      - "apis/proto/**"
      - "versions/GO_VERSION"
  pull_request:
    paths:
      - "apis/proto/**"
      - "versions/GO_VERSION"

jobs:
  build:
    name: build all
    runs-on: ubuntu-latest
    container:
      image: vdaas/vald-ci-container:nightly
    steps:
      - uses: actions/checkout@v2
      - name: build protobuf
        run: |
          make proto/all
