name: "ChatOps help"
on:
  pull_request:
    types: [opened]
jobs:
  print-help:
    name: print help
    runs-on: ubuntu-latest
    steps:
      - name: comment to PR
        run: |
          PR_COMMENTS=`curl ${API_URL}?per_page=10000`
          COMMENT_BODY=`echo -E $PR_COMMENTS | jq 'last(.[] | select(.user.login == "vdaas-ci") | select(.body | test("^\\\\*\\\\*\\\\[CHATOPS:HELP")) | .body)' -r`

          if [ "$COMMENT_BODY" = "null" ]; then
            # curl -o chatops_commands.md https://raw.githubusercontent.com/vdaas/vald/master/.github/chatops_commands.md
            curl -o chatops_commands.md https://raw.githubusercontent.com/vdaas/vald/ci/run-tests/exclude-hack-codes/.github/chatops_commands.md
            BODY=`echo chatops_commands.md | sed ':a;N;$!ba;s/\n/\\\\n/g'`
            curl --include --verbose --fail \
            -H "Accept: application/json" \
            -H "Content-Type:application/json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            --request POST \
            --data "{\"body\": \"**[CHATOPS:HELP]** ChatOps commands.\\n${BODY}\"}" \
            $API_URL
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
          API_URL: ${{ github.event.pull_request.comments_url }}
          PR_NUM: ${{ github.event.issue.number }}
