name: 'Build docker image: gateway-vald'
on:
  push:
    paths:
      - 'internal/*'
      - 'internal/*/*'
      - 'internal/*/*/*'
      - 'internal/*/*/*/*'
      - 'apis/grpc/*/*'
      - 'pkg/gateway/vald/*'
      - 'pkg/gateway/vald/*/*'
      - 'pkg/gateway/vald/*/*/*'
      - 'cmd/gateway/vald/*'
      - 'dockers/base/Dockerfile'
      - 'dockers/gateway/vald/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        echo 'Build docker image'
        make dockers-gateway-vald-image
    - name: login to DockerHub
      run: |
        echo 'Login to DockerHub'
        echo ${DOCKERHUB_PASS} | docker login --username ${{ DOCKERHUB_USER }} --password-stdin
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    - name: push to DockerHub
      run: |
        echo 'Push to DockerHub'
        imagename=`make dockers-gateway-vald-image-name`
        docker push ${imagename}
