name: update protobuf
on:
  push:
    tags:
       - '*.*.*'
       - 'v*.*.*'
       - '*.*.*-*'
       - 'v*.*.*-*'

jobs:
  dispatches:
    name: Dispatches
    runs-on: ubuntu-latest
    steps:
      - name: client-go
        run: |
          curl --fail -u "${USER}:${TOKEN}" -X POST https://api.github.com/repos/${REPO}/dispatches -H 'Accept: application/vnd.github.everest-preview+json' --data '{"event_type": "update-protobuf"}'
        env:
          REPO: vdaas/vald-client-go
          USER: ${{ secrets.DISPATCH_USER }}
          TOKEN: ${{ secrets.DISPATCH_TOKEN }}
      - name: client-java
        run: |
          curl --fail -u "${USER}:${TOKEN}" -X POST https://api.github.com/repos/${REPO}/dispatches -H 'Accept: application/vnd.github.everest-preview+json' --data '{"event_type": "update-protobuf"}'
        env:
          REPO: vdaas/vald-client-java
          USER: ${{ secrets.DISPATCH_USER }}
          TOKEN: ${{ secrets.DISPATCH_TOKEN }}
      - name: client-python
        run: |
          curl --fail -u "${USER}:${TOKEN}" -X POST https://api.github.com/repos/${REPO}/dispatches -H 'Accept: application/vnd.github.everest-preview+json' --data '{"event_type": "update-protobuf"}'
        env:
          REPO: vdaas/vald-client-python
          USER: ${{ secrets.DISPATCH_USER }}
          TOKEN: ${{ secrets.DISPATCH_TOKEN }}
      - name: client-node
        run: |
          curl --fail -u "${USER}:${TOKEN}" -X POST https://api.github.com/repos/${REPO}/dispatches -H 'Accept: application/vnd.github.everest-preview+json' --data '{"event_type": "update-protobuf"}'
        env:
          REPO: vdaas/vald-client-node
          USER: ${{ secrets.DISPATCH_USER }}
          TOKEN: ${{ secrets.DISPATCH_TOKEN }}
