#
# Copyright (C) 2019-2020 Vdaas.org Vald team ( kpango, rinx, kmrmt )
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{ $isDaemonSet := false }}
{{- if .Values.agent.externalTrafficPolicy }}
{{- if eq .Values.agent.externalTrafficPolicy "Local" }}
{{ $isDaemonSet = true }}
{{- end }}
{{- end }}
apiVersion: apps/v1
{{- if $isDaemonSet }}
kind: DaemonSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ .Values.agent.name }}
  labels:
    app: {{ .Values.agent.name }}
spec:
  {{- if $isDaemonSet }}
  {{- else }}
  progressDeadlineSeconds: {{ .Values.agent.progressDeadlineSeconds }}
  replicas: {{ .Values.agent.minReplicas }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.agent.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.agent.name }}
  {{- if $isDaemonSet }}
  updateStrategy:
  {{- else }}
  strategy:
  {{- end }}
    rollingUpdate:
      {{- if $isDaemonSet }}
      {{- else }}
      maxSurge: {{ .Values.agent.rollingUpdate.maxSurge }}
      {{- end }}
      maxUnavailable: {{ .Values.agent.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.agent.name }}
    spec:
      {{- if .Values.agent.initContainers }}
      initContainers:
        {{- $initContainers := dict "initContainers" .Values.agent.initContainers "Values" .Values "namespace" .Release.Namespace -}}
        {{- include "vald.initContainers" $initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.agent.name }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          {{- $servers := dict "Values" .Values.agent.server_config "default" .Values.defaults.server_config }}
          {{- include "vald.containerPorts" $servers | nindent 10 }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            {{- toYaml .Values.agent.env | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.agent.name }}-config
              mountPath: /etc/server/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: {{ .Values.agent.terminationGracePeriodSeconds }}
      volumes:
        - name: {{ .Values.agent.name }}-config
          configMap:
            defaultMode: 420
            name: {{ .Values.agent.name }}-config
status:
